name: Update Contributions and Statistics

on:
  push:
    branches: [main]
  workflow_dispatch: # run manually from actions tab
  schedule:
  - cron: 0 0 1 * * # run once a month at midnight

permissions: {} # Set permissions at the job level.

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 3
  UV_EXCLUDE_NEWER: 1 week # ignore packages published in the last week

jobs:

  update-contributions:
    if: github.repository_owner == 'afuetterer'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        python-version: '3.14'
        enable-cache: true
        prune-cache: false
    - run: uv run scripts/fetch.py --repos-file=scripts/repos.txt --user-id=MDQ6VXNlcjM1MjI1NTc2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: uvx --with=humanize --from=cogapp cog -r README.md

    - name: Generate the user stats image
      # Ref: https://github.com/cicirello/user-statistician?tab=readme-ov-file#inputs
      uses: cicirello/user-statistician@36500351ea14b69e68217d4c89eb0f3f06680b17 # v1.26.3
      with:
        image-file: images/statistics.svg
        commit-and-push: false
        include-title: false
        featured-repository: oaipmh-scythe
        hide-keys: private mostStarred mostForked
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - uses: EndBug/add-and-commit@cc9c08ba6c8df3b93a8f2db63e89b98368ae2ae8 # v11.1.1
      with:
        add: |
          README.md
          images/statistics.svg
        default_author: github_actions
        message: 'chore: update contributions'
