name: Update Statistics

on:
  workflow_dispatch: # run manually from actions tab
  schedule:
  - cron: 0 0 * * 1 # run once a week at monday midnight

permissions:
  contents: read

jobs:
  update-statistics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Generate the user stats image
      # Ref: https://github.com/cicirello/user-statistician?tab=readme-ov-file#inputs
      uses: cicirello/user-statistician@24d5642dfb851e6072721d73031629de20c84fb3 # v1.23.0
      with:
        image-file: images/statistics.svg
        include-title: false
        featured-repository: oaipmh-scythe
        hide-keys: private mostStarred
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
